---
title: "Data exploration"
author: "Carl Yang"
date: "June 5, 2019"
output: html_document
---
```{r}
suppressWarnings(library(tidyverse))
library(ggplot2)
library(tidyverse)
library(gridExtra)
library(knitr)
library(pander)
library(dplyr)
HY = read.csv("data/HY_TEST.csv")
```

```{r}
colnames(HY)[1] <- "Date"
#head(HY, 1)

#HY %>% mutate(Date = as.Date(.$Date, format="%m/%d/%Y"))


HY$Date = as.Date(HY$Date, format="%m/%d/%Y")

```

For Coupon

```{r}
quantile(HY$coupon, na.rm = TRUE)
HY <- mutate(HY,coupon_group = cut(coupon, breaks = c(0, 6.125, 7.375, 8.625, 15), labels = c("Q1","Q2","Q3","Q4")))
```

```{r}
library(lubridate)
Coupon = HY %>% group_by(Year = year(Date), coupon_group) %>% na.omit() %>% 
  summarize(Mean = mean(as.numeric(total_return_mtd), na.rm  = T),
            SD = sd(as.numeric(total_return_mtd), na.rm = T)) %>% data.frame()

Coupon

ggplot(Coupon, aes(x = Year, y = Mean, color = coupon_group, group = coupon_group)) +
  geom_line(size = 0.7) +
  scale_x_continuous(breaks = seq(2007, 2019, 1)) +
  theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Annual Total Return by Coupon Group",
       y = "Mean Total Return in %",
       color = "Level of Coupon (Low to High)")


```

OAS(Spread)

```{r}
quantile(HY$oas, na.rm = TRUE)
HY <- mutate(HY,oas_group = cut(oas, breaks = c(-30129.8086, 302.1879, 444.1890, 677.7465, 806094.3125), labels = c("Q1","Q2","Q3","Q4")))

Spread = HY %>% group_by(Year = year(Date), oas_group) %>%
  summarize(Mean = mean(as.numeric(total_return_mtd), na.rm = T),
            SD = sd(as.numeric(total_return_mtd), na.rm = T)) %>% data.frame()

ggplot(Spread, aes(x = Year, y = Mean, color = oas_group, group = oas_group)) +
  geom_line(size = 0.7) +
  scale_x_continuous(breaks = seq(2007, 2019, 1)) +
  theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Annual Total Return by Spread (OAS) Group",
       y = "Mean Total Return in %",
       color = "Level of Spread(OAS) (Low to High)")

ggplot(Spread, aes(x = Year, y = SD, color = oas_group, group = oas_group)) +
  geom_line(size = 0.7) +
  scale_x_continuous(breaks = seq(2007, 2019, 1)) +
  theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Standard Deviation of Annual Total Return by Spread (OAS) Group",
       y = "SD of Total Return in %",
       color = "Level of Spread(OAS) (Low to High)")
```

For Duration

```{r}
quantile(HY$duration, na.rm = TRUE)
HY <- mutate(HY,duration_group = cut(duration, breaks = c(-9.279527, 2.560661, 3.948706, 5.208673, 19.636396), labels = c("Q1","Q2","Q3","Q4")))

Duration = HY %>% group_by(Year = year(Date), duration_group) %>% na.omit() %>%
  summarize(Mean = mean(as.numeric(total_return_mtd), na.rm = T),
            SD = sd(as.numeric(total_return_mtd), na.rm = T)) %>% data.frame()

ggplot(Duration, aes(x = Year, y = Mean, color = duration_group, group = duration_group)) +
  geom_line(size = 0.7) +
  scale_x_continuous(breaks = seq(2007, 2019, 1)) +
  theme(plot.title = element_text(hjust = 0.5),axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(title = "Annual Total Return by Duration Group",
       y = "Mean Total Return in %",
       color = "Level of Duration (Low to High)")
```

